<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Here we provide a detailed analysis using more sophisticated statistics techniques.">

<title>Analysis – MA 415 Data Detectives Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">MA 415 Data Detectives Final Project</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./big_picture.html"> 
<span class="menu-text">Boom, Bust and Balance - Between The Lines of Income and Interest Rates</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./analysis.html" aria-current="page"> 
<span class="menu-text">Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data.html"> 
<span class="menu-text">Data</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#objective-and-research-questions" id="toc-objective-and-research-questions" class="nav-link" data-scroll-target="#objective-and-research-questions">Objective and Research Questions</a></li>
  <li><a href="#motivating-figures-and-tables-demographic-factors" id="toc-motivating-figures-and-tables-demographic-factors" class="nav-link" data-scroll-target="#motivating-figures-and-tables-demographic-factors">Motivating Figures and Tables: Demographic Factors</a></li>
  <li><a href="#motivating-figures-and-tables-interest-rates" id="toc-motivating-figures-and-tables-interest-rates" class="nav-link" data-scroll-target="#motivating-figures-and-tables-interest-rates">Motivating Figures and Tables: Interest Rates</a></li>
  </ul></li>
  <li><a href="#modeling-and-inference" id="toc-modeling-and-inference" class="nav-link" data-scroll-target="#modeling-and-inference">Modeling and Inference</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis</h1>
</div>

<div>
  <div class="description">
    Here we provide a detailed analysis using more sophisticated statistics techniques.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><img src="images/anlysisCover.png" class="img-fluid"></p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<section id="objective-and-research-questions" class="level3">
<h3 class="anchored" data-anchor-id="objective-and-research-questions">Objective and Research Questions</h3>
<p>The goal of our analysis is to examine how macroeconomic trends in the aftermath of the 2008 recession, such as shifting interest rates, affected different racial and socioeconomic groups in the United States. We aim to answer some of the following general research questions:</p>
<ul>
<li>How do income and employment differ across gender, race, and education levels during periods of economic downturn?</li>
<li>What factors contribute to upward economic mobility?</li>
<li>Are there persistent racial disparities in long-term wealth accumulation?</li>
</ul>
<p>To limit the scope of the project, we decided to look at the age cohort of people born between 1957 and 1964, represented by the Bureau of Labor Statistics’ NLS 79 survey, who were working adults at the time of the recession. Looking at this population, some of the following questions for analysis arise:</p>
<ul>
<li>What effect did falling interest rates during the recession have on income? Can this relationship be modeled</li>
<li>Did the recession exacerbate income inequality differently along racial, socioeconomic, regional, or other lines?</li>
</ul>
</section>
<section id="motivating-figures-and-tables-demographic-factors" class="level3">
<h3 class="anchored" data-anchor-id="motivating-figures-and-tables-demographic-factors">Motivating Figures and Tables: Demographic Factors</h3>
<p>The following graphs explore some of the relationships between variables in our data to motivate this goal.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/aretha graphs-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This box plot explores the difference in income along gender and racial lines. Across all regions, men appear to make more money than women. However, this effect is particularly pronounced in the South and West regions, where the box plot indicates that a higher proportion of women do not make any income. This higher number of zero-income observations causes some issues for analysis to be accounted for during outlier removal. The graph also highlights the potential difference in effect of income declines across groups.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/ran graphs-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="motivating-figures-and-tables-interest-rates" class="level3">
<h3 class="anchored" data-anchor-id="motivating-figures-and-tables-interest-rates">Motivating Figures and Tables: Interest Rates</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/datacombination-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="modeling-and-inference" class="level2">
<h2 class="anchored" data-anchor-id="modeling-and-inference">Modeling and Inference</h2>
<p>First tried with outliers and had bad figures, and we determined there were severe outliers impacting our model.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/outliers-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We therefore used R script like below to remove these and create a new dataset specifically for modeling.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load  merged dataset</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>nls_with_rates <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"dataset/nls_with_rates_full.csv"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Calculate IQR boundaries</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>Q1 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(nls_with_rates<span class="sc">$</span>Income, <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>Q3 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(nls_with_rates<span class="sc">$</span>Income, <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>IQR_value <span class="ot">&lt;-</span> Q3 <span class="sc">-</span> Q1</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>lower_bound <span class="ot">&lt;-</span> Q1 <span class="sc">-</span> <span class="fl">0.24</span> <span class="sc">*</span> IQR_value <span class="co">#lots of 0 (n/a) data</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>upper_bound <span class="ot">&lt;-</span> Q3 <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> IQR_value</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Filter out the outliers</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>nls_no_outliers <span class="ot">&lt;-</span> nls_with_rates <span class="sc">%&gt;%</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Income <span class="sc">&gt;=</span> lower_bound <span class="sc">&amp;</span> Income <span class="sc">&lt;=</span> upper_bound)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Save it</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(nls_no_outliers, <span class="st">"dataset/nls_no_outliers.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>After cleaning the data with the script, we began creating our model. After reading the “No Outliers” dataset, we filtered the data by the income years of interest (2006, 2008, and 2010). We also transformed the data by changing the education levels to binned groups (“Less than HS”, “High School”, “Some College”, and “College+” (College+ standing for college graduate or more)) and baseline of “Never Married” for <code>Marital Status</code>. The remaining baselines were determined through alphabetical order automatically through the model (which has been addressed in our conclusions).</p>
<p>After omitting NA values for the bins, we utilized <code>lm</code> to create a linear model, testing covariates of <code>Race</code>, <code>Sex</code>, <code>Marital Status</code>, <code>Age_2010</code> (Age at Year 2010), <code>Region</code>, <code>edu_bin</code> (education group bins), and <code>avg_LT_rate</code> (average long-term interest rates) and received the following model summary statistics.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Coefficients</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Std. Error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;|t|)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Signif.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">19662.672</td>
<td style="text-align: right;">5425.858</td>
<td style="text-align: right;">3.624</td>
<td style="text-align: right;">2.91e-04</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">RaceHispanic</td>
<td style="text-align: right;">2807.627</td>
<td style="text-align: right;">669.492</td>
<td style="text-align: right;">4.194</td>
<td style="text-align: right;">2.76e-05</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceNon-Black/Non-Hispanic</td>
<td style="text-align: right;">2993.485</td>
<td style="text-align: right;">508.561</td>
<td style="text-align: right;">5.886</td>
<td style="text-align: right;">4.06e-09</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">SexMale</td>
<td style="text-align: right;">14242.081</td>
<td style="text-align: right;">410.012</td>
<td style="text-align: right;">34.736</td>
<td style="text-align: right;">&lt; 2e-16</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marital_StatusDivorced</td>
<td style="text-align: right;">4408.501</td>
<td style="text-align: right;">722.159</td>
<td style="text-align: right;">6.105</td>
<td style="text-align: right;">1.06e-09</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marital_StatusMarried</td>
<td style="text-align: right;">6627.434</td>
<td style="text-align: right;">627.593</td>
<td style="text-align: right;">10.560</td>
<td style="text-align: right;">&lt; 2e-16</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marital_StatusSeparated</td>
<td style="text-align: right;">-1682.529</td>
<td style="text-align: right;">1146.696</td>
<td style="text-align: right;">-1.467</td>
<td style="text-align: right;">1.42e-01</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Marital_StatusWidowed</td>
<td style="text-align: right;">-677.400</td>
<td style="text-align: right;">1637.284</td>
<td style="text-align: right;">-0.414</td>
<td style="text-align: right;">6.79e-01</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age_2010</td>
<td style="text-align: right;">-4.619</td>
<td style="text-align: right;">91.514</td>
<td style="text-align: right;">-0.050</td>
<td style="text-align: right;">9.60e-01</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">RegionNortheast</td>
<td style="text-align: right;">4010.788</td>
<td style="text-align: right;">679.436</td>
<td style="text-align: right;">5.903</td>
<td style="text-align: right;">3.66e-09</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RegionSouth</td>
<td style="text-align: right;">445.695</td>
<td style="text-align: right;">528.300</td>
<td style="text-align: right;">0.844</td>
<td style="text-align: right;">3.99e-01</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">RegionWest</td>
<td style="text-align: right;">2824.512</td>
<td style="text-align: right;">647.839</td>
<td style="text-align: right;">4.360</td>
<td style="text-align: right;">1.31e-05</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edu_binHigh School</td>
<td style="text-align: right;">10851.067</td>
<td style="text-align: right;">1621.460</td>
<td style="text-align: right;">6.692</td>
<td style="text-align: right;">2.30e-11</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">edu_binSome College</td>
<td style="text-align: right;">18365.587</td>
<td style="text-align: right;">1646.517</td>
<td style="text-align: right;">11.154</td>
<td style="text-align: right;">&lt; 2e-16</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edu_binCollege+</td>
<td style="text-align: right;">29432.746</td>
<td style="text-align: right;">1654.119</td>
<td style="text-align: right;">17.794</td>
<td style="text-align: right;">&lt; 2e-16</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg_LT_rate</td>
<td style="text-align: right;">-2523.204</td>
<td style="text-align: right;">567.790</td>
<td style="text-align: right;">-4.444</td>
<td style="text-align: right;">8.91e-06</td>
<td style="text-align: center;">***</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Model Fit Statistics</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Residual SE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Degrees of Freedom</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">R-squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Adjusted R-squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">F-statistic</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">P-Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">22033</td>
<td style="text-align: right;">11871</td>
<td style="text-align: right;">0.2009</td>
<td style="text-align: right;">0.1999</td>
<td style="text-align: right;">199</td>
<td style="text-align: left;">&lt; 2e-16</td>
</tr>
</tbody>
</table>


</div>
</div>
<ul>
<li><p>Our model has a r-squared value of 0.2009, indicating that 20.09% of the variance in our model is explained by the model’s covariates. The adjusted r-squared value is slightly lower at 0.1999, meaning our model explains 19.99% of the variance in the model after adjusting for the number of predictors.</p></li>
<li><p>The F-statistic of 199 and p-value of &lt;2e-16 (extremely close to 0) confirms that the overall model is statistically significant; Atleast some of the covariates in the model explain our response variable <code>Income</code>. Only <code>Age_2010</code> and <code>RegionSouth</code> fail to have a significant effect in explaining <code>Income</code>. The residual standard error of 22033 (roughly <code>0.5418</code> of mean income) indicates substantial noise exists in our model.</p></li>
</ul>
<p>Based on the metrics we observed, we observed our model’s diagnostic plots in the form of a residual vs.&nbsp;fitted plot and a Q-Q normality plot.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/residualplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The residual vs.&nbsp;fitted values for our model reveals funneling, indicating moderate levels of heteroscedasticity that could bias the standard errors for our coefficients. This could distort our t-test statistics and p-values and undermining the actual significance of covariates in the model.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/qqplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Analyzing our normal Q-Q plot, most points follow along the dashed diagonal line very well; most residuals are approximately normally distributed.</p></li>
<li><p>On the ends, several points stray away, reflecting a few extreme (under and over) predictions and heavier tails than a normal Gaussian distribution. These results are expected as we only trimmed the most extreme outliers and because of the nature of our data (most people cluster around the middle of the distribution, but a few people earn very little while a few earn very large sums – disparity in income distribution).</p></li>
</ul>
<p>Another consideration we made was to check for multicollinearity (for the precision of our coefficient estimates) by computing predictor-level GVIF values adjusted with degrees of freedom. All values fell below 1.5, with most covariates having GVIF values close to 1. No interaction terms were needed in our model, and our r-squared and adjusted r-squared values are not inflated by correlated predictors.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Predictor-level Variance Inflation Factors</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Predictor</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">GVIF</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">GVIF^(1/(2*Df))</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">1.338842</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.075678</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sex</td>
<td style="text-align: right;">1.028136</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.013970</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marital_Status</td>
<td style="text-align: right;">1.104040</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.012449</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age_2010</td>
<td style="text-align: right;">1.004665</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.002330</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Region</td>
<td style="text-align: right;">1.234429</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1.035725</td>
</tr>
<tr class="even">
<td style="text-align: left;">edu_bin</td>
<td style="text-align: right;">1.068939</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1.011173</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg_LT_rate</td>
<td style="text-align: right;">1.000200</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.000100</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>After checking diagnostics and GVIFs:</p>
<ul>
<li>Moderate heteroscedasticity existed (seen in residual vs.&nbsp;fitted plot).</li>
<li>Residuals in our Q-Q plot were roughly normal.</li>
<li>Relatively no multicollinearity based on the GVIFs.</li>
</ul>
<p>Our next logical step was to experiment with stabilizing the variance through transformations of our outcome.</p>
<p>We fitted various transformations, included four common ones (<code>boxcox</code> - lambda = 0.6, <code>square root</code>, <code>logarithm</code>, <code>reciprocal</code>), and compared their residual standard errors for further analysis.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Residual Standard Errors by Transformation</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Transformation</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Residual SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sqrt(Income)</td>
<td style="text-align: right;">59</td>
</tr>
<tr class="even">
<td style="text-align: left;">log(Income + 1)</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1 / Income</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">BC(λ=0.6)</td>
<td style="text-align: right;">332</td>
</tr>
</tbody>
</table>


</div>
</div>
<ul>
<li><p>For the <code>sqrt()</code> transformation, the residual SE was 59 <code>square root dollar units</code>, showing some variance stabilization but not intuitive on this scale.</p></li>
<li><p>For the <code>log()</code> transformation, the residual SE was 1 <code>log dollar unit</code>, translating to multiplicative errors of <code>~2.7x</code> in our residual calculations.</p></li>
<li><p>For the <code>1/Income</code> reciprocal transformation, the residual SE was 0. The transformation collapsed all the variation towards 0 but over compressed to the point of breaking interpretability of the coefficients.</p></li>
<li><p>For the <code>boxcox</code> transformation, the residual SE was 332 (on lambda value of 0.6), comparable to the sqrt() transform (lambda value 0.5) but non-intuitive on a different scale.</p></li>
</ul>
<p>Further analysis into the residual vs.&nbsp;fitted plots for all the transformations revealed that none of these transformations corrected for heteroscedasticity, with all showing funneling (and therefore we have omitted the plots for brevity).</p>
<p>Instead of using these transformations, we decided to keep <code>Income</code> on its original scale and correct for valid inference by using robust standard errors through <code>coeftest()</code> for unbiased point estimates and accurate standard errors, t-stat values, and p-values under heteroscedasticity</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>HC1‐Robust coeftest t‐tests for OLS Coefficients</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Std. Error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;|t|)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Signif</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">19662.672</td>
<td style="text-align: right;">5286.113</td>
<td style="text-align: right;">3.720</td>
<td style="text-align: right;">2.00e-04</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">RaceHispanic</td>
<td style="text-align: right;">2807.627</td>
<td style="text-align: right;">654.545</td>
<td style="text-align: right;">4.289</td>
<td style="text-align: right;">1.81e-05</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceNon-Black/Non-Hispanic</td>
<td style="text-align: right;">2993.485</td>
<td style="text-align: right;">501.590</td>
<td style="text-align: right;">5.968</td>
<td style="text-align: right;">2.47e-09</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">SexMale</td>
<td style="text-align: right;">14242.081</td>
<td style="text-align: right;">410.099</td>
<td style="text-align: right;">34.728</td>
<td style="text-align: right;">&lt; 2e-16</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marital_StatusDivorced</td>
<td style="text-align: right;">4408.501</td>
<td style="text-align: right;">713.909</td>
<td style="text-align: right;">6.175</td>
<td style="text-align: right;">6.83e-10</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marital_StatusMarried</td>
<td style="text-align: right;">6627.434</td>
<td style="text-align: right;">611.675</td>
<td style="text-align: right;">10.835</td>
<td style="text-align: right;">&lt; 2e-16</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marital_StatusSeparated</td>
<td style="text-align: right;">-1682.529</td>
<td style="text-align: right;">1099.353</td>
<td style="text-align: right;">-1.530</td>
<td style="text-align: right;">1.26e-01</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Marital_StatusWidowed</td>
<td style="text-align: right;">-677.400</td>
<td style="text-align: right;">1486.064</td>
<td style="text-align: right;">-0.456</td>
<td style="text-align: right;">6.49e-01</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age_2010</td>
<td style="text-align: right;">-4.619</td>
<td style="text-align: right;">92.115</td>
<td style="text-align: right;">-0.050</td>
<td style="text-align: right;">9.60e-01</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">RegionNortheast</td>
<td style="text-align: right;">4010.788</td>
<td style="text-align: right;">702.725</td>
<td style="text-align: right;">5.707</td>
<td style="text-align: right;">1.17e-08</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RegionSouth</td>
<td style="text-align: right;">445.695</td>
<td style="text-align: right;">516.859</td>
<td style="text-align: right;">0.862</td>
<td style="text-align: right;">3.89e-01</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">RegionWest</td>
<td style="text-align: right;">2824.512</td>
<td style="text-align: right;">670.018</td>
<td style="text-align: right;">4.216</td>
<td style="text-align: right;">2.51e-05</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edu_binHigh School</td>
<td style="text-align: right;">10851.067</td>
<td style="text-align: right;">1120.241</td>
<td style="text-align: right;">9.686</td>
<td style="text-align: right;">&lt; 2e-16</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">edu_binSome College</td>
<td style="text-align: right;">18365.587</td>
<td style="text-align: right;">1159.706</td>
<td style="text-align: right;">15.836</td>
<td style="text-align: right;">&lt; 2e-16</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edu_binCollege+</td>
<td style="text-align: right;">29432.746</td>
<td style="text-align: right;">1190.501</td>
<td style="text-align: right;">24.723</td>
<td style="text-align: right;">&lt; 2e-16</td>
<td style="text-align: center;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg_LT_rate</td>
<td style="text-align: right;">-2523.204</td>
<td style="text-align: right;">574.428</td>
<td style="text-align: right;">-4.393</td>
<td style="text-align: right;">1.13e-05</td>
<td style="text-align: center;">***</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>After applying robust inference with <code>coeftest()</code>, our standard errors, t-values, and p-values were adjusted. Coefficients for predictors remained the same. We clustered by <code>Case_ID</code> to check for between-person correlation, but this did not differ from the original HC1 coeftest() and did not alter conclusions, so we only reported the original results. While there were no changes to significant terms, the p-value for average long-term interest rates lowered further.</p>
<p>With valid inferences now, the last part we decided to test was the use of stepwise AIC/BIC regression for variable selection.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Variables Chosen by Stepwise AIC vs.&nbsp;BIC</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 87%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Criterion</th>
<th style="text-align: left;">Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AIC</td>
<td style="text-align: left;">Income ~ Race + Sex + Marital_Status + Region + edu_bin + avg_LT_rate</td>
</tr>
<tr class="even">
<td style="text-align: left;">BIC</td>
<td style="text-align: left;">Income ~ edu_bin + Sex + Marital_Status + Region + Race + avg_LT_rate</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Both AIC and BIC criterion based selections show the same models, omitting <code>Age_2010</code>, aligning with the <code>***</code> significance markers in our coefficient tests. While specific levels in variables (<code>RegionSouth</code>, <code>Marital_StatusSeparated</code>, etc) are not considered significant, the overall variables they belong to are significant as other levels have an effect. These stepwise regression results need to be considered with caution as heteroscedasticity violates the penalties enacted by AIC and BIC. More principled selection methods can be explored, but these are out of our scope.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Based on our diagnostics and overall checks, the following is our OLS model on the untransformed <code>Income</code> scale:</p>
<p><span class="math display">\[
\mathrm{Income}_i \;=\; \beta_0
  + \beta_{\text{Race}}
  + \beta_{\text{Sex}}
  + \beta_{\text{Marital}}
  + \beta_{\text{Region}}
  + \beta_{\text{Edu}}
  + \beta_{\text{LT Rate}}
  + \varepsilon_i
\]</span></p>
<p>Our pooled-OLS model (pooling 2006, 2008, and 2010 while retaining only long-term average interest rates) with HC1-Robust SEs (checked for person-clustered SEs) provided us with the following key takeaways:</p>
<p><strong>Education and Gender remain the most dominant effects on Income</strong>: - With all other predictors held constant, males earned on average <code>~$14,242</code> more per year than females regardless of the year.</p>
<ul>
<li><p>Averaging across 2006-2010, college graduates earned nearly <code>~$30000</code> more than those who did not attend high school (“Less than HS” is part of the base estimate as an indicator variable). The gap is of a similar magnitude in each year, which suggests that a college education was stable even during the 2008 downturn.</p></li>
<li><p>Each successive education category translated to about <code>$7000-$11000</code> in additional annual earnings, a pattern stable across 2006-2010.</p></li>
</ul>
<p><strong>Race, Marriage, and Region have strong secondary effects</strong>: - Individuals identifying as <code>Non-Black/Non-Hispanic</code> and <code>Hispanic</code> earned nearly <code>$2993</code> and <code>$2807</code> more than those identifying as <code>Black / African-American</code> (baseline), potentially indicative of <code>Black / African-American</code> individuals being disproportionately affected with relation to earnings.</p>
<ul>
<li><p>Married individuals earned <code>$6627</code> more than those who never married (baseline). Divorced individuals earned <code>$4408</code> more, while separated and widowed individuals earned <code>$1682</code> and <code>$677</code> less, respectively. Marriage might have had an economical advantage (potentially dual incomes, shared expenses, financial support from spouse).</p></li>
<li><p>Compared to those living in the central United States (baseline), residents in the Northeast earned <code>~$4010</code> more, and residents living in the West earned <code>~2824</code> more. The South had a modest increase in earnings of <code>~$445</code>. These differences may reflect economic opportunities, urbanization, and higher costs of living.</p></li>
</ul>
<p><strong>Macroeconomic conditions have an impact</strong>:<br>
By omitting factor levels for each year, the long-term interest rates are isolated and show the marginal cyclical effect of the rates, not conflated with other effects embedded in the model and intercept (ex: wage growth, recessionary gaps, stimulus programs).</p>
<ul>
<li>A one-percent point rise in the average long-term interest rate is associated with a <code>$2523</code> reduction in income on average across the three years, even after pooling across the recessionary dip in 2008.</li>
</ul>
<p>This reduction does not account for total shock in 2008, rather reflecting on the credit-cost sensitivity, explaining the average difference in income due to the change in borrowing costs with all other predictors fixed.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/sussmanbu\.github\.io\/ma4615-sp25-final-project-datadetectives\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>