---
title: "Blog Post #1"
author: "Patrio Marcus, Chandini Toleti, Ranbir, Aretha McDonald, Emir"
date: "2025-02-26"
date-modified: "2025-02-26"
draft: FALSE
---
# Blog post 1
This is DataDetectives' first blog post, where we describe potential datasets to use for our final project. 

## DataSet 1 - Wealth of Households (2022)
::: {.border}
130 rows x 20 columns | U.S. Census Bureau’s 2023 Survey of Income and Program Participation (SIPP) | [DataSet](https://www.census.gov/library/publications/2024/demo/p70br-202.html)
:::
The data is well organized but it is not in tsv/csv format so it will have to be converted before being loaded and cleaned. Questions we hope to address: What is the distribution of household wealth across different demographic and economic groups?, How do asset ownership and debt-holding rates vary among households?, What insights can be drawn about economic well-being based on household wealth variations? Some foreseen challenges:  It may be difficult to determine whether factors like education and income cause differences in wealth or are merely associated with them, Variability in how households report asset values and debt could introduce inconsistencies in wealth calculations, and The dataset reflects household wealth at the end of 2022, a period influenced by inflation, market fluctuations, and post-pandemic recovery, which could affect interpretability.

## DataSet 2 - Public Water Use

::: {.border}
253 columns x 16384 rows | The U.S. Geological Survey | [DataSet](https://www.usgs.gov/mission-areas/water-resources/science/water-use-united-states#overview)
:::

We hope to use groundwater consumption and withdrawal data from the U.S. geological survey for our final project. This data outlines monthly public supply, irrigation, and thermoelectric water use from 2009 - 2020. The dataset, which comes from a federal source, already comes in a CSV file, so it is easy to clean, read, and manage. With this information, we hope to address the question: Do different communities’ drinking water lead to health disparities? However, this leads to the challenges with this particular dataset. On its own, the dataset doesn’t provide information that can answer a question related to racial disparities. In order to answer our questions we would need to collect US Census Data, which will give us demographics (age/race) for the particular year we decide to evaluate. While census data is robust, we will be able to filter the information to better support this initial dataset. 

## DataSet 3 - Infant Mortality by Race

::: {.border}
11 columns x 12689 rows | CCD for public access | [DataSet](https://catalog.data.gov/dataset/infant-neonatal-postneonatal-fetal-and-perinatal-mortality-rates-by-detailed-race-and-hisp-016ed)
:::

One potential data set we can use describes infant mortality rates for mothers of different races. This information has few columns, mainly one detailing the number of cases of infant mortality/1000 births. However, the dataset has lots of rows, including this estimate for 12689 different points. Additionally, the data is organized as a CSV file and is easy to load and clean. With this information, we hope to address infant mortality discrepancies to determine race discrepancies in women’s healthcare. This is an intersectional issue that I hope to combine with data about access to healthcare. I see challenges of extracting a lot of different visualizations from the data because the columns appear slightly trivial/simple. As a result, we will need to combine other forms of data (maybe census data or another dataset detailing healthcare access) to create a variety of visualizations. 

